name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello message
        run: echo "Checking if google is up..."
      - name: check google
        run: ping google.com
        if = success()
      - name: Print success message
        run: echo "Google is up!"
      - name: Print failure message
        run: echo "Google is down!"

