name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello message
        run: echo "Hello Satish, GitHub Actions is working!"