name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello message
        run: echo "Checking if google is up..."
      - name: check google
        run: ping google.com
      - name: Print success message
        run: echo "Google is up!"
        if: success()
      - name: Print failure message
        run: echo "Google is down!"
        if: failure()
      - name: Print final message
        run: echo "Hello World Workflow completed!"  
